# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0002_hivedatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivedatamodel',
            name='addInformationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
