# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0004_auto_20180522_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivedatamodel',
            name='motherBee',
            field=models.NullBooleanField(default=False),
        ),
    ]
