# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0006_auto_20180529_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivedatamodel',
            name='addInformationDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
